package com.github.nscuro.bradamsang.ui;

import burp.ITab;
import com.github.nscuro.bradamsang.BurpExtension;
import com.github.nscuro.bradamsang.ExtensionSettingsProvider;
import com.github.nscuro.bradamsang.command.NativeCommandExecutor;
import com.github.nscuro.bradamsang.util.BurpLogger;
import com.github.nscuro.bradamsang.util.WslSupport;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.JPanel;
import java.awt.Component;
import java.awt.Insets;
import java.util.List;
import java.util.Optional;

public class SettingsTab implements ITab, ExtensionSettingsProvider {

    private final NativeCommandExecutor nativeCommandExecutor;
    private final WslSupport wslSupport;
    private final BurpLogger logger;

    public SettingsTab(final NativeCommandExecutor nativeCommandExecutor, final BurpLogger logger) {
        this.nativeCommandExecutor = nativeCommandExecutor;
        this.wslSupport = new WslSupport(nativeCommandExecutor);
        this.logger = logger;
    }

    @Override
    public String getTabCaption() {
        return BurpExtension.EXTENSION_NAME;
    }

    @Override
    public Component getUiComponent() {
        return null;
    }

    @Override
    public Optional<String> getRadamsaExecutablePath() {
        return Optional.empty();
    }

    @Override
    public int getPayloadCount() {
        return 0;
    }

    @Override
    public List<String> getSamplePaths() {
        return null;
    }

    @Override
    public boolean isWslModeEnabled() {
        return false;
    }

    @Override
    public Optional<String> getWslDistributionName() {
        return Optional.empty();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

}
